### ISSUE TITLE
Build spatial database and API (Epoch)

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#91]
Also we need someone building the spatial database and APi.

Start exploring options for doing this. We have data that maps into locations and organs and information about reference 

Need to do spacial queries (e.g., find all data that is withing a given radius of some "HubMap" tissue sample).

This is a new API "spatial-api" not "ontology-api".  Need to gather requirements, use cases, and do a design (this is an Epoch).

**Comment by shirey** [comment]
Worth looking at..
https://www.youtube.com/watch?v=gY3_-LIoKaU
https://portal.hubmapconsortium.org/ccf-eui

**Comment by shirey** [comment]
Waiting for from Jonathan and Bruce:
  - the information about what file in these datasets, and what inside that file we use for cell information
  - specification of how 
  - query examples/use cases

**Comment by shirey** [comment]
Spec
https://docs.google.com/document/d/1EMjTLXOG_8PzHC5fDchhNdIfOrHwhDsdlN1AViP6szU/edit?usp=sharing

**Comment by shirey** [comment]
Reference organs are here: https://ccf-api.hubmapconsortium.org/#/operations/reference-organs
Bruce will add additional information to these definitions to allow us to translate to Male and Female body spaces.

These are the individual organ structures, no translation to Male and Female body space needed because they are already specified in Male/Female body space in this file:
https://github.com/hubmapconsortium/hubmap-ontology/blob/master/source_data/generated-reference-spatial-entities.jsonld
